# Generated by Django 6.0.5 on 2026-05-10 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_music_album_artist__e74ad4_idx_and_more'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'is_public'], name='playlists_p_user_id_acd1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'updated_at'], name='playlists_p_user_id_548a36_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['name'], name='playlists_p_name_c54c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistsong',
            index=models.Index(fields=['playlist', 'position'], name='playlists_p_playlis_fca9f3_idx'),
        ),
    ]
