# Generated by Django 6.0.5 on 2026-06-10 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='playlists.PlaylistSong', to='music.song'),
        ),
        migrations.AddIndex(
            model_name='playlistsong',
            index=models.Index(fields=['playlist', 'position'], name='playlists_p_playlis_fca9f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'song')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'is_public'], name='playlists_p_user_id_acd1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'updated_at'], name='playlists_p_user_id_548a36_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['name'], name='playlists_p_name_c54c4e_idx'),
        ),
    ]
