# Generated by Django 6.0.5 on 2026-07-01 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_userartist'),
        ('playlists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_liked_songs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_liked_songs', True)), fields=('user',), name='unique_liked_songs_playlist_per_user'),
        ),
    ]
