# Generated by Django 6.0.5 on 2026-05-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_spotify_id_album_deezer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
