# Generated by Django 6.0.5 on 2026-05-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_music_album_artist__e74ad4_idx_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['song', 'user'], name='users_liste_song_id_4cc726_idx'),
        ),
    ]
