# Generated by Django 6.0.5 on 2026-07-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLibrary',
        ),
    ]
