# Generated by Django 6.0.5 on 2026-07-01 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_userartist'),
        ('users', '0003_partition_listeninghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='song',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='listened_by', to='music.song'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
