# Generated by Django 6.0.5 on 2026-06-10 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('genres', models.JSONField(default=list)),
                ('followers', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'indexes': [models.Index(fields=['name'], name='music_artis_name_e97718_idx'), models.Index(fields=['popularity'], name='music_artis_popular_80e400_idx'), models.Index(fields=['followers'], name='music_artis_followe_60cee3_idx'), models.Index(fields=['name', 'popularity'], name='music_artis_name_1df5b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cover_url', models.URLField(blank=True)),
                ('release_date', models.CharField(max_length=20)),
                ('album_type', models.CharField(max_length=50)),
                ('total_tracks', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField()),
                ('track_number', models.IntegerField(default=1)),
                ('popularity', models.IntegerField(default=0)),
                ('preview_url', models.URLField(blank=True, max_length=500)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist')),
            ],
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['name'], name='music_album_name_d80369_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_date'], name='music_album_release_5ffcba_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'release_date'], name='music_album_artist__e74ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['album_type', 'release_date'], name='music_album_album_t_b7fecc_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='music_song_title_8e56ff_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['popularity'], name='music_song_popular_af7fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', 'popularity'], name='music_song_artist__fc092c_idx'),
        ),
    ]
