# Generated by Django 6.0.5 on 2026-05-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'release_date'], name='music_album_artist__e74ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['album_type', 'release_date'], name='music_album_album_t_b7fecc_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['followers'], name='music_artis_followe_60cee3_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name', 'popularity'], name='music_artis_name_1df5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', 'popularity'], name='music_song_artist__fc092c_idx'),
        ),
    ]
