# Generated by Django 6.0.5 on 2026-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
