# Generated by Django 6.0.5 on 2026-05-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_music_album_artist__e74ad4_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='spotify_id',
            new_name='deezer_id',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='spotify_id',
            new_name='deezer_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify_id',
            new_name='deezer_id',
        ),
    ]
